//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SelfService.MyAge", ConfigurationName="IAge")]
public interface IAge
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.MyAge/IAge/HowOldAmI", ReplyAction="http://SelfService.MyAge/IAge/HowOldAmIResponse")]
    string HowOldAmI(System.DateTime birthDay);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.MyAge/IAge/HowOldAmI", ReplyAction="http://SelfService.MyAge/IAge/HowOldAmIResponse")]
    System.Threading.Tasks.Task<string> HowOldAmIAsync(System.DateTime birthDay);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAgeChannel : IAge, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AgeClient : System.ServiceModel.ClientBase<IAge>, IAge
{
    
    public AgeClient()
    {
    }
    
    public AgeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AgeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AgeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AgeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string HowOldAmI(System.DateTime birthDay)
    {
        return base.Channel.HowOldAmI(birthDay);
    }
    
    public System.Threading.Tasks.Task<string> HowOldAmIAsync(System.DateTime birthDay)
    {
        return base.Channel.HowOldAmIAsync(birthDay);
    }
}
