//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmiClient.BmiCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BmiCalc.BmiCalculatorSoap")]
    public interface BmiCalculatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculator", ReplyAction="*")]
        double Calculator(double height, double weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculator", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculatorAsync(double height, double weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BmiCalculatorSoapChannel : BmiClient.BmiCalc.BmiCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BmiCalculatorSoapClient : System.ServiceModel.ClientBase<BmiClient.BmiCalc.BmiCalculatorSoap>, BmiClient.BmiCalc.BmiCalculatorSoap {
        
        public BmiCalculatorSoapClient() {
        }
        
        public BmiCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BmiCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BmiCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BmiCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Calculator(double height, double weight) {
            return base.Channel.Calculator(height, weight);
        }
        
        public System.Threading.Tasks.Task<double> CalculatorAsync(double height, double weight) {
            return base.Channel.CalculatorAsync(height, weight);
        }
    }
}
