//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SelfService.HarryPotter", ConfigurationName="IHarryPotterBooks")]
public interface IHarryPotterBooks
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.HarryPotter/IHarryPotterBooks/BookName", ReplyAction="http://SelfService.HarryPotter/IHarryPotterBooks/BookNameResponse")]
    string BookName(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.HarryPotter/IHarryPotterBooks/BookName", ReplyAction="http://SelfService.HarryPotter/IHarryPotterBooks/BookNameResponse")]
    System.Threading.Tasks.Task<string> BookNameAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHarryPotterBooksChannel : IHarryPotterBooks, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HarryPotterBooksClient : System.ServiceModel.ClientBase<IHarryPotterBooks>, IHarryPotterBooks
{
    
    public HarryPotterBooksClient()
    {
    }
    
    public HarryPotterBooksClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HarryPotterBooksClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HarryPotterBooksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HarryPotterBooksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string BookName(string name)
    {
        return base.Channel.BookName(name);
    }
    
    public System.Threading.Tasks.Task<string> BookNameAsync(string name)
    {
        return base.Channel.BookNameAsync(name);
    }
}
