//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klienten.WeatherPrediction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherPrediction.WeatherSoap")]
    public interface WeatherSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Klienten.WeatherPrediction.HelloWorldResponse HelloWorld(Klienten.WeatherPrediction.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Klienten.WeatherPrediction.HelloWorldResponse> HelloWorldAsync(Klienten.WeatherPrediction.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name WeatherForecastResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeatherForecast", ReplyAction="*")]
        Klienten.WeatherPrediction.WeatherForecastResponse WeatherForecast(Klienten.WeatherPrediction.WeatherForecastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeatherForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<Klienten.WeatherPrediction.WeatherForecastResponse> WeatherForecastAsync(Klienten.WeatherPrediction.WeatherForecastRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.WeatherPrediction.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Klienten.WeatherPrediction.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.WeatherPrediction.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Klienten.WeatherPrediction.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeatherForecastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeatherForecast", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.WeatherPrediction.WeatherForecastRequestBody Body;
        
        public WeatherForecastRequest() {
        }
        
        public WeatherForecastRequest(Klienten.WeatherPrediction.WeatherForecastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WeatherForecastRequestBody {
        
        public WeatherForecastRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeatherForecastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeatherForecastResponse", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.WeatherPrediction.WeatherForecastResponseBody Body;
        
        public WeatherForecastResponse() {
        }
        
        public WeatherForecastResponse(Klienten.WeatherPrediction.WeatherForecastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeatherForecastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WeatherForecastResult;
        
        public WeatherForecastResponseBody() {
        }
        
        public WeatherForecastResponseBody(string WeatherForecastResult) {
            this.WeatherForecastResult = WeatherForecastResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherSoapChannel : Klienten.WeatherPrediction.WeatherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherSoapClient : System.ServiceModel.ClientBase<Klienten.WeatherPrediction.WeatherSoap>, Klienten.WeatherPrediction.WeatherSoap {
        
        public WeatherSoapClient() {
        }
        
        public WeatherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Klienten.WeatherPrediction.HelloWorldResponse Klienten.WeatherPrediction.WeatherSoap.HelloWorld(Klienten.WeatherPrediction.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Klienten.WeatherPrediction.HelloWorldRequest inValue = new Klienten.WeatherPrediction.HelloWorldRequest();
            inValue.Body = new Klienten.WeatherPrediction.HelloWorldRequestBody();
            Klienten.WeatherPrediction.HelloWorldResponse retVal = ((Klienten.WeatherPrediction.WeatherSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Klienten.WeatherPrediction.HelloWorldResponse> Klienten.WeatherPrediction.WeatherSoap.HelloWorldAsync(Klienten.WeatherPrediction.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Klienten.WeatherPrediction.HelloWorldResponse> HelloWorldAsync() {
            Klienten.WeatherPrediction.HelloWorldRequest inValue = new Klienten.WeatherPrediction.HelloWorldRequest();
            inValue.Body = new Klienten.WeatherPrediction.HelloWorldRequestBody();
            return ((Klienten.WeatherPrediction.WeatherSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Klienten.WeatherPrediction.WeatherForecastResponse Klienten.WeatherPrediction.WeatherSoap.WeatherForecast(Klienten.WeatherPrediction.WeatherForecastRequest request) {
            return base.Channel.WeatherForecast(request);
        }
        
        public string WeatherForecast() {
            Klienten.WeatherPrediction.WeatherForecastRequest inValue = new Klienten.WeatherPrediction.WeatherForecastRequest();
            inValue.Body = new Klienten.WeatherPrediction.WeatherForecastRequestBody();
            Klienten.WeatherPrediction.WeatherForecastResponse retVal = ((Klienten.WeatherPrediction.WeatherSoap)(this)).WeatherForecast(inValue);
            return retVal.Body.WeatherForecastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Klienten.WeatherPrediction.WeatherForecastResponse> Klienten.WeatherPrediction.WeatherSoap.WeatherForecastAsync(Klienten.WeatherPrediction.WeatherForecastRequest request) {
            return base.Channel.WeatherForecastAsync(request);
        }
        
        public System.Threading.Tasks.Task<Klienten.WeatherPrediction.WeatherForecastResponse> WeatherForecastAsync() {
            Klienten.WeatherPrediction.WeatherForecastRequest inValue = new Klienten.WeatherPrediction.WeatherForecastRequest();
            inValue.Body = new Klienten.WeatherPrediction.WeatherForecastRequestBody();
            return ((Klienten.WeatherPrediction.WeatherSoap)(this)).WeatherForecastAsync(inValue);
        }
    }
}
