//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klienten.Oscars {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Oscars.OscarNominatedMoviesSoap")]
    public interface OscarNominatedMoviesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Movies", ReplyAction="*")]
        void Movies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Movies", ReplyAction="*")]
        System.Threading.Tasks.Task MoviesAsync();
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWinningMovies", ReplyAction="*")]
        Klienten.Oscars.GetAllWinningMoviesResponse GetAllWinningMovies(Klienten.Oscars.GetAllWinningMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWinningMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<Klienten.Oscars.GetAllWinningMoviesResponse> GetAllWinningMoviesAsync(Klienten.Oscars.GetAllWinningMoviesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWinningMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWinningMovies", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.Oscars.GetAllWinningMoviesRequestBody Body;
        
        public GetAllWinningMoviesRequest() {
        }
        
        public GetAllWinningMoviesRequest(Klienten.Oscars.GetAllWinningMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWinningMoviesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public GetAllWinningMoviesRequestBody() {
        }
        
        public GetAllWinningMoviesRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWinningMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWinningMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.Oscars.GetAllWinningMoviesResponseBody Body;
        
        public GetAllWinningMoviesResponse() {
        }
        
        public GetAllWinningMoviesResponse(Klienten.Oscars.GetAllWinningMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWinningMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllWinningMoviesResult;
        
        public GetAllWinningMoviesResponseBody() {
        }
        
        public GetAllWinningMoviesResponseBody(string GetAllWinningMoviesResult) {
            this.GetAllWinningMoviesResult = GetAllWinningMoviesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OscarNominatedMoviesSoapChannel : Klienten.Oscars.OscarNominatedMoviesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OscarNominatedMoviesSoapClient : System.ServiceModel.ClientBase<Klienten.Oscars.OscarNominatedMoviesSoap>, Klienten.Oscars.OscarNominatedMoviesSoap {
        
        public OscarNominatedMoviesSoapClient() {
        }
        
        public OscarNominatedMoviesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OscarNominatedMoviesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OscarNominatedMoviesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OscarNominatedMoviesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Movies() {
            base.Channel.Movies();
        }
        
        public System.Threading.Tasks.Task MoviesAsync() {
            return base.Channel.MoviesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Klienten.Oscars.GetAllWinningMoviesResponse Klienten.Oscars.OscarNominatedMoviesSoap.GetAllWinningMovies(Klienten.Oscars.GetAllWinningMoviesRequest request) {
            return base.Channel.GetAllWinningMovies(request);
        }
        
        public string GetAllWinningMovies(string year) {
            Klienten.Oscars.GetAllWinningMoviesRequest inValue = new Klienten.Oscars.GetAllWinningMoviesRequest();
            inValue.Body = new Klienten.Oscars.GetAllWinningMoviesRequestBody();
            inValue.Body.year = year;
            Klienten.Oscars.GetAllWinningMoviesResponse retVal = ((Klienten.Oscars.OscarNominatedMoviesSoap)(this)).GetAllWinningMovies(inValue);
            return retVal.Body.GetAllWinningMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Klienten.Oscars.GetAllWinningMoviesResponse> Klienten.Oscars.OscarNominatedMoviesSoap.GetAllWinningMoviesAsync(Klienten.Oscars.GetAllWinningMoviesRequest request) {
            return base.Channel.GetAllWinningMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Klienten.Oscars.GetAllWinningMoviesResponse> GetAllWinningMoviesAsync(string year) {
            Klienten.Oscars.GetAllWinningMoviesRequest inValue = new Klienten.Oscars.GetAllWinningMoviesRequest();
            inValue.Body = new Klienten.Oscars.GetAllWinningMoviesRequestBody();
            inValue.Body.year = year;
            return ((Klienten.Oscars.OscarNominatedMoviesSoap)(this)).GetAllWinningMoviesAsync(inValue);
        }
    }
}
