//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klienten.WorstMaleActor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorstMaleActor.MaleActorSoap")]
    public interface MaleActorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAllBadActors", ReplyAction="*")]
        void AddAllBadActors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAllBadActors", ReplyAction="*")]
        System.Threading.Tasks.Task AddAllBadActorsAsync();
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBadActors", ReplyAction="*")]
        Klienten.WorstMaleActor.GetAllBadActorsResponse GetAllBadActors(Klienten.WorstMaleActor.GetAllBadActorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBadActors", ReplyAction="*")]
        System.Threading.Tasks.Task<Klienten.WorstMaleActor.GetAllBadActorsResponse> GetAllBadActorsAsync(Klienten.WorstMaleActor.GetAllBadActorsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBadActorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBadActors", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.WorstMaleActor.GetAllBadActorsRequestBody Body;
        
        public GetAllBadActorsRequest() {
        }
        
        public GetAllBadActorsRequest(Klienten.WorstMaleActor.GetAllBadActorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBadActorsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public GetAllBadActorsRequestBody() {
        }
        
        public GetAllBadActorsRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBadActorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBadActorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.WorstMaleActor.GetAllBadActorsResponseBody Body;
        
        public GetAllBadActorsResponse() {
        }
        
        public GetAllBadActorsResponse(Klienten.WorstMaleActor.GetAllBadActorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBadActorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllBadActorsResult;
        
        public GetAllBadActorsResponseBody() {
        }
        
        public GetAllBadActorsResponseBody(string GetAllBadActorsResult) {
            this.GetAllBadActorsResult = GetAllBadActorsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaleActorSoapChannel : Klienten.WorstMaleActor.MaleActorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaleActorSoapClient : System.ServiceModel.ClientBase<Klienten.WorstMaleActor.MaleActorSoap>, Klienten.WorstMaleActor.MaleActorSoap {
        
        public MaleActorSoapClient() {
        }
        
        public MaleActorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaleActorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaleActorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaleActorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddAllBadActors() {
            base.Channel.AddAllBadActors();
        }
        
        public System.Threading.Tasks.Task AddAllBadActorsAsync() {
            return base.Channel.AddAllBadActorsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Klienten.WorstMaleActor.GetAllBadActorsResponse Klienten.WorstMaleActor.MaleActorSoap.GetAllBadActors(Klienten.WorstMaleActor.GetAllBadActorsRequest request) {
            return base.Channel.GetAllBadActors(request);
        }
        
        public string GetAllBadActors(string year) {
            Klienten.WorstMaleActor.GetAllBadActorsRequest inValue = new Klienten.WorstMaleActor.GetAllBadActorsRequest();
            inValue.Body = new Klienten.WorstMaleActor.GetAllBadActorsRequestBody();
            inValue.Body.year = year;
            Klienten.WorstMaleActor.GetAllBadActorsResponse retVal = ((Klienten.WorstMaleActor.MaleActorSoap)(this)).GetAllBadActors(inValue);
            return retVal.Body.GetAllBadActorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Klienten.WorstMaleActor.GetAllBadActorsResponse> Klienten.WorstMaleActor.MaleActorSoap.GetAllBadActorsAsync(Klienten.WorstMaleActor.GetAllBadActorsRequest request) {
            return base.Channel.GetAllBadActorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Klienten.WorstMaleActor.GetAllBadActorsResponse> GetAllBadActorsAsync(string year) {
            Klienten.WorstMaleActor.GetAllBadActorsRequest inValue = new Klienten.WorstMaleActor.GetAllBadActorsRequest();
            inValue.Body = new Klienten.WorstMaleActor.GetAllBadActorsRequestBody();
            inValue.Body.year = year;
            return ((Klienten.WorstMaleActor.MaleActorSoap)(this)).GetAllBadActorsAsync(inValue);
        }
    }
}
