//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarryPotterBooks_Win.HarryPotterBooks {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HarryPotterBooks.HarryPotterBooksSoap")]
    public interface HarryPotterBooksSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookName", ReplyAction="*")]
        HarryPotterBooks_Win.HarryPotterBooks.BookNameResponse BookName(HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookName", ReplyAction="*")]
        System.Threading.Tasks.Task<HarryPotterBooks_Win.HarryPotterBooks.BookNameResponse> BookNameAsync(HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookName", Namespace="http://tempuri.org/", Order=0)]
        public HarryPotterBooks_Win.HarryPotterBooks.BookNameRequestBody Body;
        
        public BookNameRequest() {
        }
        
        public BookNameRequest(HarryPotterBooks_Win.HarryPotterBooks.BookNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public BookNameRequestBody() {
        }
        
        public BookNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public HarryPotterBooks_Win.HarryPotterBooks.BookNameResponseBody Body;
        
        public BookNameResponse() {
        }
        
        public BookNameResponse(HarryPotterBooks_Win.HarryPotterBooks.BookNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookNameResult;
        
        public BookNameResponseBody() {
        }
        
        public BookNameResponseBody(string BookNameResult) {
            this.BookNameResult = BookNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HarryPotterBooksSoapChannel : HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HarryPotterBooksSoapClient : System.ServiceModel.ClientBase<HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap>, HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap {
        
        public HarryPotterBooksSoapClient() {
        }
        
        public HarryPotterBooksSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HarryPotterBooksSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HarryPotterBooksSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HarryPotterBooksSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HarryPotterBooks_Win.HarryPotterBooks.BookNameResponse HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap.BookName(HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest request) {
            return base.Channel.BookName(request);
        }
        
        public string BookName(string name) {
            HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest inValue = new HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest();
            inValue.Body = new HarryPotterBooks_Win.HarryPotterBooks.BookNameRequestBody();
            inValue.Body.name = name;
            HarryPotterBooks_Win.HarryPotterBooks.BookNameResponse retVal = ((HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap)(this)).BookName(inValue);
            return retVal.Body.BookNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HarryPotterBooks_Win.HarryPotterBooks.BookNameResponse> HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap.BookNameAsync(HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest request) {
            return base.Channel.BookNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<HarryPotterBooks_Win.HarryPotterBooks.BookNameResponse> BookNameAsync(string name) {
            HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest inValue = new HarryPotterBooks_Win.HarryPotterBooks.BookNameRequest();
            inValue.Body = new HarryPotterBooks_Win.HarryPotterBooks.BookNameRequestBody();
            inValue.Body.name = name;
            return ((HarryPotterBooks_Win.HarryPotterBooks.HarryPotterBooksSoap)(this)).BookNameAsync(inValue);
        }
    }
}
