//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EmmyAndersson.SelfService", ConfigurationName="IBmi")]
public interface IBmi
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EmmyAndersson.SelfService/IBmi/Calculate", ReplyAction="http://EmmyAndersson.SelfService/IBmi/CalculateResponse")]
    string Calculate(double height, double weight);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EmmyAndersson.SelfService/IBmi/Calculate", ReplyAction="http://EmmyAndersson.SelfService/IBmi/CalculateResponse")]
    System.Threading.Tasks.Task<string> CalculateAsync(double height, double weight);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBmiChannel : IBmi, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BmiClient : System.ServiceModel.ClientBase<IBmi>, IBmi
{
    
    public BmiClient()
    {
    }
    
    public BmiClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BmiClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BmiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BmiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Calculate(double height, double weight)
    {
        return base.Channel.Calculate(height, weight);
    }
    
    public System.Threading.Tasks.Task<string> CalculateAsync(double height, double weight)
    {
        return base.Channel.CalculateAsync(height, weight);
    }
}
