//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAge_Win.AgeCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgeCalc.MyAgeCalculatorSoap")]
    public interface MyAgeCalculatorSoap {
        
        // CODEGEN: Generating message contract since element name CalculateAgeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateAge", ReplyAction="*")]
        MyAge_Win.AgeCalc.CalculateAgeResponse CalculateAge(MyAge_Win.AgeCalc.CalculateAgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateAge", ReplyAction="*")]
        System.Threading.Tasks.Task<MyAge_Win.AgeCalc.CalculateAgeResponse> CalculateAgeAsync(MyAge_Win.AgeCalc.CalculateAgeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateAgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateAge", Namespace="http://tempuri.org/", Order=0)]
        public MyAge_Win.AgeCalc.CalculateAgeRequestBody Body;
        
        public CalculateAgeRequest() {
        }
        
        public CalculateAgeRequest(MyAge_Win.AgeCalc.CalculateAgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateAgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime birthDay;
        
        public CalculateAgeRequestBody() {
        }
        
        public CalculateAgeRequestBody(System.DateTime birthDay) {
            this.birthDay = birthDay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateAgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateAgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyAge_Win.AgeCalc.CalculateAgeResponseBody Body;
        
        public CalculateAgeResponse() {
        }
        
        public CalculateAgeResponse(MyAge_Win.AgeCalc.CalculateAgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateAgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateAgeResult;
        
        public CalculateAgeResponseBody() {
        }
        
        public CalculateAgeResponseBody(string CalculateAgeResult) {
            this.CalculateAgeResult = CalculateAgeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyAgeCalculatorSoapChannel : MyAge_Win.AgeCalc.MyAgeCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyAgeCalculatorSoapClient : System.ServiceModel.ClientBase<MyAge_Win.AgeCalc.MyAgeCalculatorSoap>, MyAge_Win.AgeCalc.MyAgeCalculatorSoap {
        
        public MyAgeCalculatorSoapClient() {
        }
        
        public MyAgeCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyAgeCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyAgeCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyAgeCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyAge_Win.AgeCalc.CalculateAgeResponse MyAge_Win.AgeCalc.MyAgeCalculatorSoap.CalculateAge(MyAge_Win.AgeCalc.CalculateAgeRequest request) {
            return base.Channel.CalculateAge(request);
        }
        
        public string CalculateAge(System.DateTime birthDay) {
            MyAge_Win.AgeCalc.CalculateAgeRequest inValue = new MyAge_Win.AgeCalc.CalculateAgeRequest();
            inValue.Body = new MyAge_Win.AgeCalc.CalculateAgeRequestBody();
            inValue.Body.birthDay = birthDay;
            MyAge_Win.AgeCalc.CalculateAgeResponse retVal = ((MyAge_Win.AgeCalc.MyAgeCalculatorSoap)(this)).CalculateAge(inValue);
            return retVal.Body.CalculateAgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyAge_Win.AgeCalc.CalculateAgeResponse> MyAge_Win.AgeCalc.MyAgeCalculatorSoap.CalculateAgeAsync(MyAge_Win.AgeCalc.CalculateAgeRequest request) {
            return base.Channel.CalculateAgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyAge_Win.AgeCalc.CalculateAgeResponse> CalculateAgeAsync(System.DateTime birthDay) {
            MyAge_Win.AgeCalc.CalculateAgeRequest inValue = new MyAge_Win.AgeCalc.CalculateAgeRequest();
            inValue.Body = new MyAge_Win.AgeCalc.CalculateAgeRequestBody();
            inValue.Body.birthDay = birthDay;
            return ((MyAge_Win.AgeCalc.MyAgeCalculatorSoap)(this)).CalculateAgeAsync(inValue);
        }
    }
}
