//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klienten.Namesdagar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Namesdagar.NamnsdagGeneratorSoap")]
    public interface NamnsdagGeneratorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameDays", ReplyAction="*")]
        void NameDays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameDays", ReplyAction="*")]
        System.Threading.Tasks.Task NameDaysAsync();
        
        // CODEGEN: Generating message contract since element name inputName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameDayDateReturner", ReplyAction="*")]
        Klienten.Namesdagar.NameDayDateReturnerResponse NameDayDateReturner(Klienten.Namesdagar.NameDayDateReturnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameDayDateReturner", ReplyAction="*")]
        System.Threading.Tasks.Task<Klienten.Namesdagar.NameDayDateReturnerResponse> NameDayDateReturnerAsync(Klienten.Namesdagar.NameDayDateReturnerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameDayDateReturnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameDayDateReturner", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.Namesdagar.NameDayDateReturnerRequestBody Body;
        
        public NameDayDateReturnerRequest() {
        }
        
        public NameDayDateReturnerRequest(Klienten.Namesdagar.NameDayDateReturnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameDayDateReturnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputName;
        
        public NameDayDateReturnerRequestBody() {
        }
        
        public NameDayDateReturnerRequestBody(string inputName) {
            this.inputName = inputName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameDayDateReturnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameDayDateReturnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Klienten.Namesdagar.NameDayDateReturnerResponseBody Body;
        
        public NameDayDateReturnerResponse() {
        }
        
        public NameDayDateReturnerResponse(Klienten.Namesdagar.NameDayDateReturnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameDayDateReturnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameDayDateReturnerResult;
        
        public NameDayDateReturnerResponseBody() {
        }
        
        public NameDayDateReturnerResponseBody(string NameDayDateReturnerResult) {
            this.NameDayDateReturnerResult = NameDayDateReturnerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NamnsdagGeneratorSoapChannel : Klienten.Namesdagar.NamnsdagGeneratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NamnsdagGeneratorSoapClient : System.ServiceModel.ClientBase<Klienten.Namesdagar.NamnsdagGeneratorSoap>, Klienten.Namesdagar.NamnsdagGeneratorSoap {
        
        public NamnsdagGeneratorSoapClient() {
        }
        
        public NamnsdagGeneratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NamnsdagGeneratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamnsdagGeneratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamnsdagGeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NameDays() {
            base.Channel.NameDays();
        }
        
        public System.Threading.Tasks.Task NameDaysAsync() {
            return base.Channel.NameDaysAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Klienten.Namesdagar.NameDayDateReturnerResponse Klienten.Namesdagar.NamnsdagGeneratorSoap.NameDayDateReturner(Klienten.Namesdagar.NameDayDateReturnerRequest request) {
            return base.Channel.NameDayDateReturner(request);
        }
        
        public string NameDayDateReturner(string inputName) {
            Klienten.Namesdagar.NameDayDateReturnerRequest inValue = new Klienten.Namesdagar.NameDayDateReturnerRequest();
            inValue.Body = new Klienten.Namesdagar.NameDayDateReturnerRequestBody();
            inValue.Body.inputName = inputName;
            Klienten.Namesdagar.NameDayDateReturnerResponse retVal = ((Klienten.Namesdagar.NamnsdagGeneratorSoap)(this)).NameDayDateReturner(inValue);
            return retVal.Body.NameDayDateReturnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Klienten.Namesdagar.NameDayDateReturnerResponse> Klienten.Namesdagar.NamnsdagGeneratorSoap.NameDayDateReturnerAsync(Klienten.Namesdagar.NameDayDateReturnerRequest request) {
            return base.Channel.NameDayDateReturnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Klienten.Namesdagar.NameDayDateReturnerResponse> NameDayDateReturnerAsync(string inputName) {
            Klienten.Namesdagar.NameDayDateReturnerRequest inValue = new Klienten.Namesdagar.NameDayDateReturnerRequest();
            inValue.Body = new Klienten.Namesdagar.NameDayDateReturnerRequestBody();
            inValue.Body.inputName = inputName;
            return ((Klienten.Namesdagar.NamnsdagGeneratorSoap)(this)).NameDayDateReturnerAsync(inValue);
        }
    }
}
