//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SelfService.NextThousand", ConfigurationName="INextThousand")]
public interface INextThousand
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.NextThousand/INextThousand/NextThousandDays", ReplyAction="http://SelfService.NextThousand/INextThousand/NextThousandDaysResponse")]
    System.DateTime NextThousandDays(System.DateTime birthDay);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.NextThousand/INextThousand/NextThousandDays", ReplyAction="http://SelfService.NextThousand/INextThousand/NextThousandDaysResponse")]
    System.Threading.Tasks.Task<System.DateTime> NextThousandDaysAsync(System.DateTime birthDay);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INextThousandChannel : INextThousand, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NextThousandClient : System.ServiceModel.ClientBase<INextThousand>, INextThousand
{
    
    public NextThousandClient()
    {
    }
    
    public NextThousandClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NextThousandClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NextThousandClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NextThousandClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime NextThousandDays(System.DateTime birthDay)
    {
        return base.Channel.NextThousandDays(birthDay);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> NextThousandDaysAsync(System.DateTime birthDay)
    {
        return base.Channel.NextThousandDaysAsync(birthDay);
    }
}
